services:
  - type: web
    name: plagiarism-checker
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://plagiarism-checkerr.vercel.app,http://localhost:3000
